[package]
name = "queens"
version = "0.1.0"
authors = ["Clement Cherlin <https://github.com/Mooninaut/>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
